# Generated by Django 3.2.10 on 2022-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
    ]
