# Generated by Django 3.2.10 on 2022-04-04 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220404_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sort',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后编辑时间'),
        ),
    ]
