# Generated by Django 3.2.10 on 2022-04-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='公司名称')),
                ('entitle', models.CharField(max_length=64, verbose_name='公司名称')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('tel', models.CharField(max_length=16, verbose_name='公司电话')),
                ('fax', models.CharField(max_length=16, verbose_name='公司传真')),
                ('slug', models.URLField(verbose_name='公司网址')),
                ('email', models.EmailField(max_length=254, verbose_name='公司邮箱')),
                ('bank_name', models.CharField(max_length=32, verbose_name='银行名称')),
                ('account_title', models.CharField(max_length=32, verbose_name='帐户名称')),
                ('bank_account', models.CharField(max_length=32, verbose_name='银行帐户')),
                ('bank_number', models.CharField(max_length=24, verbose_name='银行行号')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='LOGO')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
    ]
